from sqlmodel import Session, select

from app.models.ingredient import Ingredient

FREQUENT_INGREDIENTS = [
    # ── 빈출 (frequent) ──────────────────────────────────────────────────────
    {"name": "계란", "category": "달걀"},
    {"name": "김치", "category": "발효"},
    {"name": "돼지고기", "category": "단백질"},
    {"name": "대파", "category": "채소"},
    {"name": "두부", "category": "발효"},
    {"name": "양파", "category": "채소"},
    {"name": "마늘", "category": "채소"},
    {"name": "당근", "category": "채소"},
    {"name": "감자", "category": "채소"},
    {"name": "고추장", "category": "양념"},
    # ── 채소 ─────────────────────────────────────────────────────────────────
    {"name": "배추", "category": "채소"},
    {"name": "무", "category": "채소"},
    {"name": "시금치", "category": "채소"},
    {"name": "상추", "category": "채소"},
    {"name": "깻잎", "category": "채소"},
    {"name": "부추", "category": "채소"},
    {"name": "콩나물", "category": "채소"},
    {"name": "숙주나물", "category": "채소"},
    {"name": "브로콜리", "category": "채소"},
    {"name": "콜리플라워", "category": "채소"},
    {"name": "고구마", "category": "채소"},
    {"name": "호박", "category": "채소"},
    {"name": "애호박", "category": "채소"},
    {"name": "단호박", "category": "채소"},
    {"name": "오이", "category": "채소"},
    {"name": "토마토", "category": "채소"},
    {"name": "방울토마토", "category": "채소"},
    {"name": "가지", "category": "채소"},
    {"name": "피망", "category": "채소"},
    {"name": "파프리카", "category": "채소"},
    {"name": "셀러리", "category": "채소"},
    {"name": "아스파라거스", "category": "채소"},
    {"name": "고사리", "category": "채소"},
    {"name": "취나물", "category": "채소"},
    {"name": "도라지", "category": "채소"},
    {"name": "연근", "category": "채소"},
    {"name": "우엉", "category": "채소"},
    {"name": "쑥갓", "category": "채소"},
    {"name": "열무", "category": "채소"},
    {"name": "청경채", "category": "채소"},
    {"name": "미나리", "category": "채소"},
    {"name": "냉이", "category": "채소"},
    {"name": "달래", "category": "채소"},
    {"name": "쑥", "category": "채소"},
    {"name": "참나물", "category": "채소"},
    {"name": "적양배추", "category": "채소"},
    {"name": "양배추", "category": "채소"},
    {"name": "케일", "category": "채소"},
    {"name": "비트", "category": "채소"},
    {"name": "래디시", "category": "채소"},
    {"name": "순무", "category": "채소"},
    {"name": "고추", "category": "채소"},
    {"name": "청양고추", "category": "채소"},
    {"name": "홍고추", "category": "채소"},
    {"name": "꽈리고추", "category": "채소"},
    {"name": "죽순", "category": "채소"},
    {"name": "생강", "category": "채소"},
    {"name": "강황", "category": "채소"},
    {"name": "고수", "category": "채소"},
    {"name": "파슬리", "category": "채소"},
    {"name": "바질", "category": "채소"},
    {"name": "민트", "category": "채소"},
    {"name": "로즈마리", "category": "채소"},
    {"name": "타임", "category": "채소"},
    {"name": "오크라", "category": "채소"},
    {"name": "루꼴라", "category": "채소"},
    # ── 과일 ─────────────────────────────────────────────────────────────────
    {"name": "사과", "category": "채소"},
    {"name": "배", "category": "채소"},
    {"name": "복숭아", "category": "채소"},
    {"name": "포도", "category": "채소"},
    {"name": "딸기", "category": "채소"},
    {"name": "블루베리", "category": "채소"},
    {"name": "라즈베리", "category": "채소"},
    {"name": "수박", "category": "채소"},
    {"name": "참외", "category": "채소"},
    {"name": "멜론", "category": "채소"},
    {"name": "바나나", "category": "채소"},
    {"name": "키위", "category": "채소"},
    {"name": "망고", "category": "채소"},
    {"name": "파인애플", "category": "채소"},
    {"name": "오렌지", "category": "채소"},
    {"name": "레몬", "category": "채소"},
    {"name": "라임", "category": "채소"},
    {"name": "자몽", "category": "채소"},
    {"name": "귤", "category": "채소"},
    {"name": "감", "category": "채소"},
    {"name": "대추", "category": "채소"},
    {"name": "자두", "category": "채소"},
    {"name": "체리", "category": "채소"},
    {"name": "살구", "category": "채소"},
    {"name": "무화과", "category": "채소"},
    {"name": "석류", "category": "채소"},
    {"name": "아보카도", "category": "채소"},
    {"name": "코코넛", "category": "채소"},
    {"name": "파파야", "category": "채소"},
    # ── 육류 ─────────────────────────────────────────────────────────────────
    {"name": "소고기", "category": "단백질"},
    {"name": "닭고기", "category": "단백질"},
    {"name": "오리고기", "category": "단백질"},
    {"name": "양고기", "category": "단백질"},
    {"name": "삼겹살", "category": "단백질"},
    {"name": "목살", "category": "단백질"},
    {"name": "등심", "category": "단백질"},
    {"name": "안심", "category": "단백질"},
    {"name": "갈비", "category": "단백질"},
    {"name": "사태", "category": "단백질"},
    {"name": "차돌박이", "category": "단백질"},
    {"name": "항정살", "category": "단백질"},
    {"name": "닭가슴살", "category": "단백질"},
    {"name": "닭다리", "category": "단백질"},
    {"name": "닭날개", "category": "단백질"},
    {"name": "베이컨", "category": "단백질"},
    {"name": "햄", "category": "단백질"},
    {"name": "소시지", "category": "단백질"},
    {"name": "스팸", "category": "단백질"},
    {"name": "런천미트", "category": "단백질"},
    # ── 해산물 ───────────────────────────────────────────────────────────────
    {"name": "고등어", "category": "단백질"},
    {"name": "삼치", "category": "단백질"},
    {"name": "갈치", "category": "단백질"},
    {"name": "꽁치", "category": "단백질"},
    {"name": "조기", "category": "단백질"},
    {"name": "명태", "category": "단백질"},
    {"name": "대구", "category": "단백질"},
    {"name": "연어", "category": "단백질"},
    {"name": "참치", "category": "단백질"},
    {"name": "광어", "category": "단백질"},
    {"name": "우럭", "category": "단백질"},
    {"name": "도미", "category": "단백질"},
    {"name": "바지락", "category": "단백질"},
    {"name": "모시조개", "category": "단백질"},
    {"name": "홍합", "category": "단백질"},
    {"name": "굴", "category": "단백질"},
    {"name": "전복", "category": "단백질"},
    {"name": "소라", "category": "단백질"},
    {"name": "꽃게", "category": "단백질"},
    {"name": "대게", "category": "단백질"},
    {"name": "새우", "category": "단백질"},
    {"name": "오징어", "category": "단백질"},
    {"name": "낙지", "category": "단백질"},
    {"name": "문어", "category": "단백질"},
    {"name": "쭈꾸미", "category": "단백질"},
    {"name": "미역", "category": "단백질"},
    {"name": "다시마", "category": "단백질"},
    {"name": "김", "category": "단백질"},
    {"name": "톳", "category": "단백질"},
    {"name": "멍게", "category": "단백질"},
    {"name": "해삼", "category": "단백질"},
    {"name": "명란", "category": "단백질"},
    {"name": "어묵", "category": "단백질"},
    {"name": "게맛살", "category": "단백질"},
    {"name": "건멸치", "category": "단백질"},
    {"name": "황태", "category": "단백질"},
    {"name": "북어", "category": "단백질"},
    {"name": "건새우", "category": "단백질"},
    # ── 유제품·달걀 ───────────────────────────────────────────────────────────
    {"name": "메추리알", "category": "달걀"},
    {"name": "우유", "category": "달걀"},
    {"name": "두유", "category": "달걀"},
    {"name": "생크림", "category": "달걀"},
    {"name": "버터", "category": "달걀"},
    {"name": "치즈", "category": "달걀"},
    {"name": "요거트", "category": "달걀"},
    {"name": "모짜렐라치즈", "category": "달걀"},
    {"name": "파마산치즈", "category": "달걀"},
    {"name": "크림치즈", "category": "달걀"},
    {"name": "연유", "category": "달걀"},
    {"name": "사워크림", "category": "달걀"},
    # ── 곡물·면·빵 ────────────────────────────────────────────────────────────
    {"name": "쌀", "category": "grain"},
    {"name": "현미", "category": "grain"},
    {"name": "찹쌀", "category": "grain"},
    {"name": "보리", "category": "grain"},
    {"name": "귀리", "category": "grain"},
    {"name": "밀가루", "category": "grain"},
    {"name": "옥수수", "category": "grain"},
    {"name": "옥수수가루", "category": "grain"},
    {"name": "메밀", "category": "grain"},
    {"name": "라면", "category": "grain"},
    {"name": "당면", "category": "grain"},
    {"name": "소면", "category": "grain"},
    {"name": "우동면", "category": "grain"},
    {"name": "스파게티", "category": "grain"},
    {"name": "쌀국수", "category": "grain"},
    {"name": "식빵", "category": "grain"},
    {"name": "바게트", "category": "grain"},
    {"name": "또띠야", "category": "grain"},
    {"name": "떡", "category": "grain"},
    {"name": "가래떡", "category": "grain"},
    {"name": "떡볶이떡", "category": "grain"},
    # ── 양념·소스 ────────────────────────────────────────────────────────────
    {"name": "간장", "category": "양념"},
    {"name": "된장", "category": "양념"},
    {"name": "쌈장", "category": "양념"},
    {"name": "소금", "category": "양념"},
    {"name": "설탕", "category": "양념"},
    {"name": "식초", "category": "양념"},
    {"name": "참기름", "category": "양념"},
    {"name": "들기름", "category": "양념"},
    {"name": "식용유", "category": "양념"},
    {"name": "올리브유", "category": "양념"},
    {"name": "후추", "category": "양념"},
    {"name": "고춧가루", "category": "양념"},
    {"name": "참깨", "category": "양념"},
    {"name": "들깨", "category": "양념"},
    {"name": "굴소스", "category": "양념"},
    {"name": "액젓", "category": "양념"},
    {"name": "멸치액젓", "category": "양념"},
    {"name": "까나리액젓", "category": "양념"},
    {"name": "미림", "category": "양념"},
    {"name": "청주", "category": "양념"},
    {"name": "맛술", "category": "양념"},
    {"name": "케첩", "category": "양념"},
    {"name": "마요네즈", "category": "양념"},
    {"name": "머스타드", "category": "양념"},
    {"name": "핫소스", "category": "양념"},
    {"name": "데리야키소스", "category": "양념"},
    {"name": "두반장", "category": "양념"},
    {"name": "XO소스", "category": "양념"},
    {"name": "피시소스", "category": "양념"},
    {"name": "스리라차", "category": "양념"},
    {"name": "발사믹식초", "category": "양념"},
    {"name": "레몬즙", "category": "양념"},
    # ── 버섯 ─────────────────────────────────────────────────────────────────
    {"name": "표고버섯", "category": "채소"},
    {"name": "느타리버섯", "category": "채소"},
    {"name": "새송이버섯", "category": "채소"},
    {"name": "팽이버섯", "category": "채소"},
    {"name": "양송이버섯", "category": "채소"},
    {"name": "송이버섯", "category": "채소"},
    {"name": "목이버섯", "category": "채소"},
    {"name": "석이버섯", "category": "채소"},
    {"name": "노루궁뎅이버섯", "category": "채소"},
    # ── 두류·견과류 ───────────────────────────────────────────────────────────
    {"name": "검은콩", "category": "발효"},
    {"name": "팥", "category": "발효"},
    {"name": "녹두", "category": "발효"},
    {"name": "강낭콩", "category": "발효"},
    {"name": "완두콩", "category": "발효"},
    {"name": "병아리콩", "category": "발효"},
    {"name": "렌틸콩", "category": "발효"},
    {"name": "아몬드", "category": "발효"},
    {"name": "호두", "category": "발효"},
    {"name": "땅콩", "category": "발효"},
    {"name": "캐슈넛", "category": "발효"},
    {"name": "피스타치오", "category": "발효"},
    {"name": "잣", "category": "발효"},
    {"name": "해바라기씨", "category": "발효"},
    {"name": "호박씨", "category": "발효"},
    {"name": "밤", "category": "발효"},
    {"name": "은행", "category": "발효"},
    {"name": "치아씨드", "category": "발효"},
    # ── 가공식품 ─────────────────────────────────────────────────────────────
    {"name": "순두부", "category": "발효"},
    {"name": "유부", "category": "발효"},
    {"name": "묵", "category": "발효"},
    {"name": "깍두기", "category": "발효"},
    {"name": "열무김치", "category": "발효"},
    {"name": "동치미", "category": "발효"},
    {"name": "참치캔", "category": "발효"},
    {"name": "골뱅이캔", "category": "발효"},
    {"name": "코코넛밀크", "category": "발효"},
    {"name": "두부면", "category": "발효"},
    {"name": "곤약", "category": "발효"},
]


def seed_frequent_ingredients(session: Session) -> None:
    """
    식재료 전체 목록을 DB에 삽입합니다.
    이미 같은 이름의 식재료가 존재하면 건너뜁니다 (idempotent).
    """
    inserted_count = 0

    for data in FREQUENT_INGREDIENTS:
        existing = session.exec(
            select(Ingredient).where(Ingredient.name == data["name"])
        ).first()

        if existing:
            continue

        session.add(Ingredient(**data))
        inserted_count += 1

    session.commit()

    if inserted_count:
        print(f"[seed] 식재료 {inserted_count}개 삽입 완료")
